### ISSUE TITLE
"No internet connection" error

### ISSUE THREAD

**Issue by tgharib** [pcloudcom/psyncgui#1]
Hi,

I am running Arch Linux and when I try to login, I get a "No internet connection" error. I tried rebooting and reinstalling openssl but that didn't seem to do anything. I launched it from the terminal and this is the output:

> psyncgui: /usr/lib/libssl.so.1.0.0: no version information available (required by psyncgui)
> psyncgui: /usr/lib/libssl.so.1.0.0: no version information available (required by psyncgui)
> psyncgui: /usr/lib/libcrypto.so.1.0.0: no version information available (required by psyncgui)
> PSTATUS_OFFLINE 
> QDateTime("Tue Apr 12 13:24:44 2016") NOTIFICATIONS (check_version): no new version - check again after 24h if app is still launced 
> NotificationsManager create 
> saveauth true username  
> login btn  11 11 11 1 
> login btn  11 11 11 1 
> destructing app

I am connected to the internet over wifi. I can login into the pcloud website and download my data from there.

**Comment by tgharib** [comment]
It appears that pcloud also isn't working on my other machine that was working yesterday so I assume the pcloud servers for this application are down at the moment.

**Comment by sapuizait** [comment]
godamn it, same problem going on since yesterday! Is this a periodical thing? and why is it only affecting Linux???

**Comment by tgharib** [comment]
@sapuizait I've since switched to syncthing (if you're interested)

**Comment by sapuizait** [comment]
thanks @tgharib, I ll have a look!

**Comment by annargrs** [comment]
same problem :(

**Comment by agriffa** [comment]
I had the same problem on Ubuntu 14.04.
Installing the pCloud update (download message from pCloud website) solved the problem for me.

**Comment by JustAnotherJack** [comment]
I'm on Ubuntu 16.04.  Didn't solve it for me.

**Comment by sapuizait** [comment]
I got in touch with the pCloud people who told me that they have given up on the previous pcloud versions and they focus their efforts on the electron client 1.2.0

I downloaded and so far it has been working fine on ubuntu 14.04 (yes yes its an old OS but I cant bother upgrading :p)

**Comment by JustAnotherJack** [comment]
Thanks,

**Comment by JustAnotherJack** [comment]
Actually, that's the version i'm having problems with.
Tech supt told me to delete some folders & restart, but that didn't help.
Gonna have to find something else.
Thanks fo your help
